import { AboutSlint, Button, VerticalBox } from "std-widgets.slint";

export component App inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;

    popup2 := PopupWindow {
        width: root.width / 2;
        height: root.height / 2;

        Rectangle {
            background: Colors.green;
            Text {
                text: "Text";
            }
        }
    }

    popup := PopupWindow {
        width: root.width / 2;
        height: root.height / 2;

        inner_context_menu := ContextMenuArea {
            Menu {
                MenuItem {
                    title: "Open popup";
                    activated => {
                        context_menu.close();
                        popup.show();
                    }
                }
            }
        }

        Rectangle {
            background: Colors.red;
            VerticalBox {
                alignment: LayoutAlignment.center;

                Button {
                    text: "Open inner context menu";
                    clicked => {
                        inner_context_menu.show({ x: 0, y: 0 });
                    }
                }

                Button {
                    text: "Open second popup";
                    clicked => {
                        // The following line must be uncommented to show the second popup
                        //popup.close();
                        popup2.show();
                    }
                }
            }
        }
    }

    context_menu := ContextMenuArea {
        Menu {
            MenuItem {
                title: "Open popup";
                activated => {
                    // The following line must be uncommented to show the first popup
                    //context_menu.close();
                    popup.show();
                }
            }
        }
    }

    Button {
        text: "Show context menu";
        clicked => {
            context_menu.show(self.absolute-position);
        }
    }
}
