import { AboutSlint, Button, VerticalBox } from "std-widgets.slint";

export component App inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;

    popup2 := PopupWindow {
        width: root.width / 2;
        height: root.height / 2;

        Rectangle {
            background: Colors.green;
            Text {
                text: "Text";
            }
        }
    }

    popup := PopupWindow {
        width: root.width / 2;
        height: root.height / 2;

        Rectangle {
            background: Colors.red;
            Button {
                text: "Open second popup";
                clicked => {
                    //popup.close();
                    popup2.show();
                }
            }
        }
    }

    context_menu := ContextMenuArea {
        Menu {
            MenuItem {
                title: "Open popup";
                activated => {
                    //context_menu.close();
                    popup.show();
                }
            }
        }
    }

    Button {
        text: "Show context menu";
        clicked => {
            context_menu.show(self.absolute-position);
        }
    }
}
